//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACWSSK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACWSSK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount:.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Label_Back {
            get {
                return ResourceManager.GetString("Label_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card / Debit Card.
        /// </summary>
        public static string Label_Card {
            get {
                return ResourceManager.GetString("Label_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Label_Done {
            get {
                return ResourceManager.GetString("Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Wallet.
        /// </summary>
        public static string Label_EWallet {
            get {
                return ResourceManager.GetString("Label_EWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate receipt.
        /// </summary>
        public static string Label_GenerateReceipt {
            get {
                return ResourceManager.GetString("Label_GenerateReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecshine App QR.
        /// </summary>
        public static string Label_LecshineApp {
            get {
                return ResourceManager.GetString("Label_LecshineApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        public static string Label_MakePayment {
            get {
                return ResourceManager.GetString("Label_MakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please move your car forward.
        /// </summary>
        public static string Label_MoveCar {
            get {
                return ResourceManager.GetString("Label_MoveCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is failed!.
        /// </summary>
        public static string Label_PaymentFailed {
            get {
                return ResourceManager.GetString("Label_PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment processing....
        /// </summary>
        public static string Label_PaymentProcessing {
            get {
                return ResourceManager.GetString("Label_PaymentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is successful!.
        /// </summary>
        public static string Label_PaymentSuccess {
            get {
                return ResourceManager.GetString("Label_PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Service.
        /// </summary>
        public static string Label_RedeemService {
            get {
                return ResourceManager.GetString("Label_RedeemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code to get E-receipt.
        /// </summary>
        public static string Label_ScanEReceipt {
            get {
                return ResourceManager.GetString("Label_ScanEReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Please scan your E-wallet QR.
        /// </summary>
        public static string Label_ScanEWallet {
            get {
                return ResourceManager.GetString("Label_ScanEWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Please scan your Lecshine QR code.
        /// </summary>
        public static string Label_ScanLecshineApp {
            get {
                return ResourceManager.GetString("Label_ScanLecshineApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code scan failed!.
        /// </summary>
        public static string Label_ScanQRFailed {
            get {
                return ResourceManager.GetString("Label_ScanQRFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Select Payment Method.
        /// </summary>
        public static string Label_SelectPaymentMethod {
            get {
                return ResourceManager.GetString("Label_SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select Service.
        /// </summary>
        public static string Label_SelectService {
            get {
                return ResourceManager.GetString("Label_SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Label_Skip {
            get {
                return ResourceManager.GetString("Label_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Please scan your card.
        /// </summary>
        public static string Label_TapCard {
            get {
                return ResourceManager.GetString("Label_TapCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string Label_TimeOutMessage {
            get {
                return ResourceManager.GetString("Label_TimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_TimeOutNo {
            get {
                return ResourceManager.GetString("Label_TimeOutNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_TimeOutYes {
            get {
                return ResourceManager.GetString("Label_TimeOutYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string Label_TryAgain {
            get {
                return ResourceManager.GetString("Label_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, Welcome!.
        /// </summary>
        public static string Label_Welcome {
            get {
                return ResourceManager.GetString("Label_Welcome", resourceCulture);
            }
        }
    }
}
